#!/bin/bash
set -e

echo '----------------------'
echo 'BEGIN: installing Yarn'
echo '----------------------'

curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -

echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

echo '-------------------'
echo 'sudo apt-get update'
sudo apt-get update

echo '----------------------------'
echo 'sudo apt-get install -y yarn'
sudo apt-get install -y yarn

echo '--------------------'
echo 'END: installing Yarn'
echo '--------------------'
