#!/bin/bash
set -e

echo '-------------------'
echo 'sudo apt-get update'
sudo apt-get update

provision/install-rvm-user
source ~/.rvm/scripts/rvm # Activate RVM

sudo provision/install-postgresql-root

echo '----------------------------------'
echo 'sudo apt-get install -y nodejs npm'
sudo apt-get install -y nodejs npm

provision/install-yarn-user

sudo apt-get install -y graphviz

echo '--------------'
echo 'psql --version'
psql --version

echo '-------'
echo 'ruby -v'
ruby -v

echo '-------'
echo 'node -v'
node -v

echo '-------------'
echo 'npm --version'
npm --version

echo '--------------'
echo 'yarn --version'
yarn --version

