#!/bin/bash
set +e

# NOTE: /home/winner/myapp/tmp/bundle is the BUNDLE_PATH directory specified in docker-compose.yml
echo '----------------------------------------------------------------------------------------------'
echo 'mkdir -p /home/winner/myapp/tmp/bundle && chown -R winner:winner /home/winner/myapp/tmp/bundle'
docker-compose run --rm -u root web bash -c 'mkdir -p /home/winner/myapp/tmp/bundle && chown -R winner:winner /home/winner/myapp/tmp/bundle'

set -e
docker/run bin/bundle_install
