#!/bin/bash

PGUSER=`cat tmp/PGUSER.txt`
PGPASSWORD=`cat tmp/PGPASSWORD.txt`

PG_VERSION="$(ls /etc/postgresql)"
DATE=`date +%Y%m%d-%H%M%S-%3N`
PG_CONF="/etc/postgresql/$PG_VERSION/main/postgresql.conf"
PG_HBA="/etc/postgresql/$PG_VERSION/main/pg_hba.conf"

echo '----------------------------------'
echo 'Backing up old PostgreSQL settings'
cp $PG_CONF /etc/postgresql/$PG_VERSION/main/postgresql-$DATE.conf
cp $PG_HBA /etc/postgresql/$PG_VERSION/main/pg_hba-$DATE.conf

echo '--------------------'
echo "Configuring $PG_CONF"
sed -i 's/^port = .*/port = 5432/' $PG_CONF
sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/" $PG_CONF

echo '-------------------'
echo "Configuring $PG_HBA"
echo "# Database administrative login by Unix domain socket" | tee $PG_HBA
echo "local   all             postgres                                peer" | tee -a $PG_HBA
echo "" | tee -a $PG_HBA
echo "# TYPE  DATABASE        USER            ADDRESS                 METHOD" | tee -a $PG_HBA
echo "" | tee -a $PG_HBA
echo "# local is for Unix domain socket connections only" | tee -a $PG_HBA
echo "local   all             all                                     md5" | tee -a $PG_HBA
echo "" | tee -a $PG_HBA
echo "# IPv4 local connections:" | tee -a $PG_HBA
echo "host    all             all             0.0.0.0/0            md5" | tee -a $PG_HBA
echo "" | tee -a $PG_HBA
echo "# IPv6 local connections:" | tee -a $PG_HBA
echo "host    all             all             ::1/128                 md5" | tee -a $PG_HBA
echo "" | tee -a $PG_HBA
echo "host    all             all             all                     md5" | tee -a $PG_HBA

echo '--------------------------'
echo 'service postgresql restart'
service postgresql restart
wait

echo '------------'
echo 'yarn install'
yarn install
wait

echo '---------------------------------------------------------------'
echo "CREATE ROLE $PGUSER WITH CREATEDB LOGIN PASSWORD '$PGPASSWORD';"
sudo -u postgres psql -c"CREATE ROLE $PGUSER WITH CREATEDB LOGIN PASSWORD '$PGPASSWORD';"
wait

echo '----------------------------------'
echo "ALTER USER $PGUSER WITH SUPERUSER;"
sudo -u postgres psql -c"ALTER USER $PGUSER WITH SUPERUSER;"
wait

echo '---------------------------------------------------'
echo "CREATE DATABASE pie_development WITH OWNER=$PGUSER;"
sudo -u postgres psql -c"CREATE DATABASE pie_development WITH OWNER=$PGUSER;"
wait

echo '--------------------------------------------'
echo "CREATE DATABASE pie_test WITH OWNER=$PGUSER;"
sudo -u postgres psql -c"CREATE DATABASE pie_test WITH OWNER=$PGUSER;"
wait

echo '---------------------------------------------------'
echo 'sudo -u postgres psql -c"create extension pgcrypto"'
sudo -u postgres psql -c"create extension pgcrypto"
wait
